In [90]:
#DE Libraries
import pandas as pd
import numpy as np
#Function to treat JSON Column
def JSONParser(data):
    import json
    j1=json.loads(data)
    return j1

#Fix Formatting for JSON Data single '' to ""
#df.str.replace("\'", "\"")

#Data Engineering JSON column
#Read in master table
masterGameDF = pd.read_csv("DataStorage/TFT_League/TFT_Master_MatchData.csv",
                           converters={'combination':JSONParser})

masterGameDF

,gameId,gameDuration,level,lastRound,Ranked,ingameDuration,combination,champion
0,KR_4242528808,2233.449951,8,37,1,2225.243408,"{'DarkStar': 2, 'Protector': 4, 'Rebel': 1, 'S...","{""JarvanIV"": {""items"": [12], ""star"": 3}, ""Sona..."
1,KR_4242528808,2233.449951,9,37,2,2225.243408,"{'Blaster': 2, 'Chrono': 1, 'Cybernetic': 1, '...","{""Malphite"": {""items"": [], ""star"": 2}, ""Blitzc..."
2,KR_4242528808,2233.449951,8,35,3,2138.763428,"{'Blaster': 3, 'Chrono': 2, 'Cybernetic': 1, '...","{""Malphite"": {""items"": [], ""star"": 2}, ""Blitzc..."
3,KR_4242528808,2233.449951,8,33,4,2003.865967,"{'Chrono': 2, 'Cybernetic': 2, 'DarkStar': 2, ...","{""Leona"": {""items"": [], ""star"": 2}, ""Mordekais..."
4,KR_4242528808,2233.449951,7,31,5,1885.395386,"{'Blaster': 1, 'DarkStar': 1, 'Demolitionist':...","{""KhaZix"": {""items"": [], ""star"": 2}, ""KaiSa"": ..."
...,...,...,...,...,...,...,...,...
79994,KR_4367610629,2171.343994,8,35,4,1931.437500,"{'Chrono': 1, 'Cybernetic': 1, 'DarkStar': 2, ...","{""TwistedFate"": {""items"": [], ""star"": 3}, ""Pop..."
79995,KR_4367610629,2171.343994,8,33,5,1815.786133,"{'Chrono': 1, 'DarkStar': 1, 'ManaReaver': 3, ...","{""Darius"": {""items"": [15, 39], ""star"": 3}, ""Ra..."
79996,KR_4367610629,2171.343994,8,30,6,1658.850586,"{'Chrono': 2, 'Cybernetic': 1, 'DarkStar': 1, ...","{""TwistedFate"": {""items"": [], ""star"": 2}, ""Mal..."
79997,KR_4367610629,2171.343994,7,28,7,1562.578125,"{'Protector': 4, 'Rebel': 3, 'Set3_Blademaster...","{""Yasuo"": {""items"": [78], ""star"": 3}, ""Sona"": ..."
79998,KR_4367610629,2171.343994,6,23,8,1264.666992,"{'Cybernetic': 1, 'DarkStar': 1, 'Demolitionis...","{""KhaZix"": {""items"": [], ""star"": 2}, ""KaiSa"": ..."

In [91]:
#convert combination to champion origin group dataFrame
champGroup = pd.DataFrame(list(masterGameDF['combination'][0:]))

#reanme some headers & fill NaN with 0
champGroup.columns= champGroup.columns.str.replace("Set3_", "")

champGroup = champGroup.fillna(0)
champGroup = champGroup.astype(int)
champGroup['']

,DarkStar,Protector,Rebel,Celestial,Mystic,StarGuardian,Blaster,Chrono,Cybernetic,Mercenary,...,Starship,Infiltrator,ManaReaver,Sniper,SpacePirate,Vanguard,Demolitionist,MechPilot,Sorcerer,TemplateTrait
0,2,4,1,3,4,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,2,1,2,1,2,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,3,0,0,1,3,2,1,1,...,1,0,0,0,0,0,0,0,0,0
3,2,0,0,1,0,0,0,2,2,0,...,0,1,1,2,1,4,0,0,0,0
4,1,0,0,0,0,0,1,0,0,1,...,0,4,0,0,0,0,1,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79994,2,0,0,0,0,3,0,1,1,0,...,0,0,0,0,0,2,0,0,6,1
79995,1,2,0,4,0,0,0,1,0,0,...,0,0,3,2,2,1,0,0,0,1
79996,1,0,1,0,0,0,0,2,1,0,...,0,2,0,0,0,0,0,0,2,1
79997,0,4,3,2,2,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
79998,1,0,0,0,0,0,0,0,1,0,...,0,4,0,0,0,0,1,1,0,0

In [105]:
# setup champion group dataframe
originDF = pd.read_csv("DataStorage/TFT_League/TFT_Champion_CurrentVersion.csv",usecols=['origin'],header=0).drop_duplicates()
originDF = originDF[0:]
originDF = originDF[0:]
originDF['origin']=originDF['origin'].str.replace(" ", "")
originDF['origin']=originDF['origin'].str.replace("-", "")
originList = list(originDF['origin'])

# sort champGroupDF by origin/Classes
originGroupDF = pd.DataFrame(champGroup,columns=originList)
classGroupDF = champGroup.drop(originList, axis=1)

print(len(originList))
# origin DF
print(originGroupDF)
# class DF
print(classGroupDF)

10
       SpacePirate  StarGuardian  Celestial  DarkStar  MechPilot  Cybernetic  \
0                0             2          3         2          0           0
1                0             1          1         0          0           1
2                0             1          0         0          0           1
3                1             0          1         2          0           2
4                0             0          0         1          3           0
...            ...           ...        ...       ...        ...         ...
79994            0             3          0         2          0           1
79995            2             0          4         1          0           0
79996            0             0          0         1          0           1
79997            0             2          2         0          0           0
79998            0             0          0         1          1           1

       Rebel  Valkyrie  Void  Chrono
0          1         0     0       0
1          2         2     1       1
2          3         1     1       2
3          0         0     0       2
4          0         2     1       0
...      ...       ...   ...     ...
79994      0         0     1       1
79995      0         0     0       1
79996      1         0     3       2
79997      3         0     0       0
79998      0         2     1       0

[79999 rows x 10 columns]
       Protector  Mystic  Blaster  Mercenary  Blademaster  Brawler  Starship  \
0              4       4        0          0            0        0         0
1              0       2        2          1            1        4         0
2              0       0        3          1            0        4         1
3              0       0        0          0            0        0         0
4              0       0        1          1            0        0         0
...          ...     ...      ...        ...          ...      ...       ...
79994          0       0        0          0            0        0         0
79995          2       0        0          0            0        0         0
79996          0       0        0          0            0        4         0
79997          4       2        0          0            2        0         0
79998          0       0        0          0            1        0         0

       Infiltrator  ManaReaver  Sniper  Vanguard  Demolitionist  Sorcerer  \
0                0           0       0         0              0         0
1                0           0       0         0              0         0
2                0           0       0         0              0         0
3                1           1       2         4              0         0
4                4           0       0         0              1         1
...            ...         ...     ...       ...            ...       ...
79994            0           0       0         2              0         6
79995            0           3       2         1              0         0
79996            2           0       0         0              0         2
79997            0           0       0         0              0         0
79998            4           0       0         0              1         0

       TemplateTrait
0                  0
1                  0
2                  0
3                  0
4                  0
...              ...
79994              1
79995              1
79996              1
79997              0
79998              0

[79999 rows x 14 columns]